### ISSUE TITLE
Convert Current Duik translations to JSON

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#37]

**Comment by oktomus** [comment]
Maybe that issue should be moved on Duik repo ?

**Comment by oktomus** [comment]
I made a [script](https://github.com/Rainbox-dev/Duik/blob/master/src/jsxTrToJson.py) to make it easier and quicker. It works perfectly for every languages except Deutsh and Polish. So before creating the final json files, I wanted to know what you think.

For the deutsch There is a problem on 1 line: 
```
DutranslatorArray.push(["A new version of Duik is available,\ngo to http://rainboxprod.coop to download it",0,"Eine neue Version von Duik ist verfügbar,\gehen sie auf http://rainboxprod.coop
 um diese herunter zu laden"]);
```
The espace g is a problem since it's not permited in json, we can write it like it but I don't think that the code that parse the json will be ok with that.

For the polish
This is not a problem, juste my script doesn't add it into the json because there is a comment at the end of the line
```
Line ignored: DutranslatorArray.push(["Select the bones and the controller before creating IK",0,"Zaznacz kość i kontroler przed utworzeniem KO"]); //KO (Kinematyka Odwrotna)

Line ignored: DutranslatorArray.push(["Duik - Creating UI",0,"Duik - Tworzenie PU"]); //PU (Panel Użytkownika)
```

You can try the script by yourself and open the json results file with firefox to check if it's correct.

For the conversion:

- Should I make my script detect comments and add them as json comment ? 
- Should I add incorrect json escapes ? 
- Or we do these little things by hand ? Much faster I think but if we need to convert again, we must not forget ^^

**Comment by Nico-Duduf** [comment]
It's an error you found in german, it should be a "new line" \n 
```
DutranslatorArray.push(["A new version of Duik is available,\ngo to http://rainboxprod.coop to download it",0,"Eine neue Version von Duik ist verfügbar,\ngehen sie auf http://rainboxprod.coop um diese herunter zu laden"]);
```

Don't worry about updating the script, the changes can be done by hand.
When JSON will be implemented in Dutranslator, we'll just have to open a jsx then save it to json to convert it, there won't be the need for a script

**Comment by Nico-Duduf** [comment]
Can you add the json files from duik here, in the example dir?
(and in the Duik repo, in the Tests/UI dir)

**Comment by oktomus** [comment]
Yep I will do that.

**Comment by oktomus** [comment]
You want to implement jsx parsing on the Dutranslator ? Is it really usefull ? If we just convert with the py script once, we'll never have to load jsx into Dutranslator.

**Comment by oktomus** [comment]
C'est fait.

**Comment by Nico-Duduf** [comment]
Great, thanks!

jsx parsing is already implemented in dutranslator ;)
It's how it works for now, until json is implemented too.
